import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Order comes from each page's `sidebar_position` and each folder's `_category_.json`.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
