import type { DaySeriesEntry } from '@/lib/analytics/day-series'
import { totalsOf } from '@/lib/analytics/day-series'
import type { ISODate } from '@/lib/dates'
import type { InsightPayload, InsightThresholds } from '@/lib/types'

export type InsightSeverity = 'low' | 'medium' | 'high' | 'win'

export type GeneratedInsight = {
  kind: string
  severity: InsightSeverity
  /** One row per rule occurrence, so dismiss/snooze survives regeneration. */
  dedupeKey: string
  payload: InsightPayload
}

export type GoalSignal = {
  id: string
  name: string
  percent: number | null
  daysRemaining: number | null
  status: string
  justCompleted?: boolean
}

export type HabitSignal = {
  id: string
  name: string
  /** Remaining opportunities this week vs remaining required completions. */
  remainingDays: number
  remainingNeeded: number
  monthlyRate: number | null
}

export type StreakSignal = {
  kind: string
  current: number
  pendingToday: boolean
  isBest: boolean
}

/**
 * Spec 18.4–18.5 — deterministic rules over the day series. Every message is an
 * observation with its numbers attached: no causal claim, no scolding, and
 * wins are generated by the same pass as warnings so the surface is never
 * only negative.
 */
export function generateInsights({
  series,
  today,
  thresholds,
  goals = [],
  habits = [],
  streaks = [],
  weekScore,
  bestWeekScore,
}: {
  /** At least the last 21 days, oldest → newest. */
  series: DaySeriesEntry[]
  today: ISODate
  thresholds: InsightThresholds
  goals?: GoalSignal[]
  habits?: HabitSignal[]
  streaks?: StreakSignal[]
  weekScore?: number | null
  bestWeekScore?: number | null
}): GeneratedInsight[] {
  const out: GeneratedInsight[] = []
  const last = (n: number) => series.slice(-n)
  const week = last(7)
  const previousWeek = series.slice(-14, -7)
  const weekTotals = totalsOf(week)
  const previousTotals = totalsOf(previousWeek)

  // Sleep deficit streak
  const trailing = [...series].reverse()
  let deficitRun = 0
  for (const entry of trailing) {
    const sleep = entry.log?.sleepHours
    if (sleep === null || sleep === undefined) break
    if (sleep < thresholds.sleepDeficitHours) deficitRun += 1
    else break
  }
  if (deficitRun >= thresholds.sleepDeficitDays) {
    out.push({
      kind: 'sleep_deficit_streak',
      severity: 'high',
      dedupeKey: `sleep_deficit_streak:${today}`,
      payload: {
        messageKey: 'sleepDeficitStreak',
        values: { hours: thresholds.sleepDeficitHours, days: deficitRun },
        href: '/analytics?metric=sleep',
      },
    })
  }

  // Sleep debt over the week
  if (
    weekTotals.daysLogged >= 4 &&
    weekTotals.avgSleepHours !== null &&
    weekTotals.avgSleepHours < thresholds.sleepDebtAvgHours
  ) {
    out.push({
      kind: 'sleep_debt',
      severity: 'medium',
      dedupeKey: `sleep_debt:${today}`,
      payload: {
        messageKey: 'sleepDebt',
        values: {
          avg: round1(weekTotals.avgSleepHours),
          target: thresholds.sleepDebtAvgHours,
        },
        n: weekTotals.daysLogged,
        href: '/analytics?metric=sleep',
      },
    })
  }

  // Entertainment creep
  const heavyDays = week.filter(
    (entry) => (entry.log?.entertainmentMinutes ?? 0) > thresholds.entertainmentDailyMinutes,
  ).length
  if (heavyDays >= thresholds.entertainmentDaysOfWeek) {
    out.push({
      kind: 'entertainment_creep',
      severity: 'medium',
      dedupeKey: `entertainment_creep:${today}`,
      payload: {
        messageKey: 'entertainmentCreep',
        values: { minutes: thresholds.entertainmentDailyMinutes, days: heavyDays },
        n: week.length,
        href: '/analytics?metric=entertainment',
      },
    })
  }

  // Exercise gap
  let exerciseGap = 0
  for (const entry of trailing) {
    if ((entry.log?.exerciseMinutes ?? 0) > 0) break
    exerciseGap += 1
  }
  if (exerciseGap >= thresholds.exerciseGapDays) {
    out.push({
      kind: 'exercise_gap',
      severity: 'medium',
      dedupeKey: `exercise_gap:${today}`,
      payload: {
        messageKey: 'exerciseGap',
        values: { days: exerciseGap },
        href: '/analytics?metric=exercise',
      },
    })
  }

  // Study slump — only when the previous week was substantial enough to compare
  if (
    previousTotals.totalStudyMinutes >= 120 &&
    weekTotals.totalStudyMinutes <=
      previousTotals.totalStudyMinutes * thresholds.studySlumpRatio
  ) {
    out.push({
      kind: 'study_slump',
      severity: 'medium',
      dedupeKey: `study_slump:${today}`,
      payload: {
        messageKey: 'studySlump',
        values: {
          current: weekTotals.totalStudyMinutes,
          previous: previousTotals.totalStudyMinutes,
        },
        href: '/analytics?metric=study',
      },
    })
  }

  // Energy decline
  if (
    weekTotals.avgEnergy !== null &&
    previousTotals.avgEnergy !== null &&
    previousTotals.avgEnergy - weekTotals.avgEnergy >= thresholds.energyDeclinePoints
  ) {
    out.push({
      kind: 'energy_decline',
      severity: 'medium',
      dedupeKey: `energy_decline:${today}`,
      payload: {
        messageKey: 'energyDecline',
        values: {
          current: round1(weekTotals.avgEnergy),
          previous: round1(previousTotals.avgEnergy),
        },
        n: weekTotals.daysLogged,
        href: '/analytics?metric=energy',
      },
    })
  }

  // Logging gap — today is excluded, an unlogged today is not yet a gap
  let loggingGap = 0
  for (const entry of trailing) {
    if (entry.date === today) continue
    if (entry.logged) break
    loggingGap += 1
  }
  if (loggingGap >= thresholds.loggingGapDays) {
    out.push({
      kind: 'logging_gap',
      severity: 'low',
      dedupeKey: `logging_gap:${today}`,
      payload: {
        messageKey: 'loggingGap',
        values: { days: loggingGap },
        href: '/daily/catch-up',
      },
    })
  }

  // Habit still reachable, but only just
  for (const habit of habits) {
    if (habit.remainingNeeded > 0 && habit.remainingNeeded === habit.remainingDays) {
      out.push({
        kind: 'habit_at_risk',
        severity: 'low',
        dedupeKey: `habit_at_risk:${habit.id}:${today}`,
        payload: { messageKey: 'habitAtRisk', values: { habit: habit.name }, href: '/habits' },
      })
    }
    if (habit.monthlyRate !== null && habit.monthlyRate >= 0.8) {
      out.push({
        kind: 'win_habit_strong',
        severity: 'win',
        dedupeKey: `win_habit_strong:${habit.id}:${monthOf(today)}`,
        payload: {
          messageKey: 'winHabitStrong',
          values: { habit: habit.name, rate: Math.round(habit.monthlyRate * 100) },
          href: '/habits',
        },
      })
    }
  }

  // Goals off pace, and goals completed
  for (const goal of goals) {
    if (
      goal.status === 'active' &&
      goal.daysRemaining !== null &&
      goal.daysRemaining <= thresholds.goalOffPaceDays &&
      (goal.percent ?? 0) < thresholds.goalOffPaceProgress
    ) {
      out.push({
        kind: 'goal_off_pace',
        severity: 'medium',
        dedupeKey: `goal_off_pace:${goal.id}:${today}`,
        payload: {
          messageKey: 'goalOffPace',
          values: {
            goal: goal.name,
            progress: Math.round(goal.percent ?? 0),
            days: goal.daysRemaining,
          },
          href: '/goals',
        },
      })
    }
    if (goal.justCompleted) {
      out.push({
        kind: 'win_goal_completed',
        severity: 'win',
        dedupeKey: `win_goal_completed:${goal.id}`,
        payload: { messageKey: 'winGoalCompleted', values: { goal: goal.name }, href: '/goals' },
      })
    }
  }

  // Streaks: one nudge while today is still open, and a win for a new best
  for (const streak of streaks) {
    if (streak.pendingToday && streak.current >= 7) {
      out.push({
        kind: 'streak_in_danger',
        severity: 'low',
        dedupeKey: `streak_in_danger:${streak.kind}:${today}`,
        payload: {
          messageKey: 'streakInDanger',
          values: { streak: streak.kind, count: streak.current },
          href: '/daily',
        },
      })
    }
    if (streak.isBest && streak.current >= 7) {
      out.push({
        kind: 'win_best_streak',
        severity: 'win',
        dedupeKey: `win_best_streak:${streak.kind}:${streak.current}`,
        payload: {
          messageKey: 'winBestStreak',
          values: { streak: streak.kind, count: streak.current },
          href: '/habits',
        },
      })
    }
  }

  if (
    weekScore !== null &&
    weekScore !== undefined &&
    bestWeekScore !== null &&
    bestWeekScore !== undefined &&
    weekScore >= bestWeekScore
  ) {
    out.push({
      kind: 'win_best_week',
      severity: 'win',
      dedupeKey: `win_best_week:${today}`,
      payload: { messageKey: 'winBestWeek', values: { score: Math.round(weekScore) } },
    })
  }

  return out
}

const SEVERITY_ORDER: Record<InsightSeverity, number> = { high: 0, medium: 1, low: 2, win: 3 }

/**
 * The dashboard shows at most three warnings plus one win: more than that and
 * the list stops being read (spec 18.4).
 */
export function selectForDashboard(insights: GeneratedInsight[]): GeneratedInsight[] {
  const sorted = [...insights].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity],
  )
  const warnings = sorted.filter((i) => i.severity !== 'win').slice(0, 3)
  const win = sorted.find((i) => i.severity === 'win')
  return win ? [...warnings, win] : warnings
}

const round1 = (n: number) => Math.round(n * 10) / 10
const monthOf = (date: ISODate) => date.slice(0, 7)
